In [398]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [399]:
train_data_=pd.read_csv("train_spaceship.csv")
train_data,test_df=train_test_split(train_data_,test_size=0.2)
test_data=pd.read_csv("test_spaceship.csv")
train_data_copy=train_data.copy()
result=pd.DataFrame()
result['PassengerId']=test_data["PassengerId"]

In [400]:
train_data.head(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
5968,6324_03,Earth,False,G/1025/S,TRAPPIST-1e,40.0,False,1.0,0.0,895.0,10.0,0.0,Eleah Hinetthews,True
500,0539_02,Europa,True,C/18/P,55 Cancri e,36.0,False,0.0,0.0,0.0,0.0,0.0,Achyon Nalanet,True
337,0378_02,Europa,True,B/11/S,55 Cancri e,21.0,False,0.0,0.0,0.0,0.0,0.0,Marfak Pirejus,True
3884,4168_02,Earth,False,E/260/P,TRAPPIST-1e,28.0,False,0.0,241.0,6.0,0.0,542.0,Elina Deckerson,False
3582,3852_01,Mars,True,F/796/P,TRAPPIST-1e,NaN,False,0.0,0.0,0.0,0.0,0.0,Tive Tepie,True

In [401]:
train_data.isna().sum()

PassengerId       0
HomePlanet      164
CryoSleep       174
Cabin           160
Destination     139
Age             142
VIP             164
RoomService     142
FoodCourt       154
ShoppingMall    166
Spa             155
VRDeck          143
Name            167
Transported       0
dtype: int64

In [402]:
del train_data['Name']
del train_data['PassengerId']
del train_data["Cabin"]
del test_df['Name']
del test_df['PassengerId']
del test_df["Cabin"]
del test_data['Name']
del test_data['PassengerId']
del test_data["Cabin"]
train_target=train_data['Transported']
test_target=test_df['Transported']
del test_df['Transported']
del train_data['Transported']

In [403]:
test_data.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,Europa,True,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,Europa,False,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,Earth,False,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0

In [404]:
train_data.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,6812.000000,6812.000000,6800.000000,6788.000000,6799.000000,6811.000000
mean,28.715942,227.734292,450.999265,174.533883,307.626710,306.103803
std,14.453950,668.725296,1630.554161,603.622521,1133.812968,1137.839778
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,54.000000,77.000000,30.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,20336.000000

In [405]:
train_data.isna().sum()

HomePlanet      164
CryoSleep       174
Destination     139
Age             142
VIP             164
RoomService     142
FoodCourt       154
ShoppingMall    166
Spa             155
VRDeck          143
dtype: int64

In [406]:
#px.histogram(train_data,x='Age',nbins=79,marginal='box',color='Transported')

In [407]:
#skew = train_data.skew().sort_values(ascending=False)
#skew

In [408]:
#px.histogram(train_data,x='RoomService',nbins=14,color='Transported')

In [409]:
#px.histogram(train_data,x='Spa',nbins=14,color='Transported')

In [410]:
#px.histogram(train_data,x='VRDeck',nbins=25,color='Transported')

In [411]:
#px.histogram(train_data,x='FoodCourt',nbins=14,color='Transported')

In [412]:
#px.histogram(train_data,x='ShoppingMall',nbins=24,color='Transported')

In [413]:
numeric_cols=list(train_data.select_dtypes(include='float64').columns)
cat_cols=list(train_data.select_dtypes(include='object').columns)
cat_cols=cat_cols
cat_cols

['HomePlanet', 'CryoSleep', 'Destination', 'VIP']

In [414]:
imputer=SimpleImputer(strategy='most_frequent')

In [415]:
imputer.fit(train_data[numeric_cols])
imputer.fit(test_df[numeric_cols])

SimpleImputer(strategy='most_frequent')

In [416]:
train_data[numeric_cols]=imputer.transform(train_data[numeric_cols])
test_df[numeric_cols]=imputer.transform(test_df[numeric_cols])
test_data[numeric_cols]=imputer.transform(test_data[numeric_cols])

imputer.fit(train_data[cat_cols])
train_data[cat_cols]=imputer.transform(train_data[cat_cols])
test_df[cat_cols]=imputer.transform(test_df[cat_cols])
test_data[cat_cols]=imputer.transform(test_data[cat_cols])

In [417]:
train_data['HomePlanet']=train_data['HomePlanet'].fillna('Unknown')
test_df['HomePlanet']=test_df['HomePlanet'].fillna('Unknown')
test_data['HomePlanet']=test_data['HomePlanet'].fillna('Unknown')

In [418]:
test_df.isna().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [419]:
train_data[cat_cols]

     HomePlanet CryoSleep  Destination    VIP
5968      Earth     False  TRAPPIST-1e  False
500      Europa      True  55 Cancri e  False
337      Europa      True  55 Cancri e  False
3884      Earth     False  TRAPPIST-1e  False
3582       Mars      True  TRAPPIST-1e  False
...         ...       ...          ...    ...
1185       Mars     False  TRAPPIST-1e  False
7297      Earth     False  TRAPPIST-1e  False
832      Europa     False  55 Cancri e  False
7324     Europa      True  TRAPPIST-1e  False
2102     Europa      True  55 Cancri e  False

[6954 rows x 4 columns]

## Scaling

In [420]:
#scaler=MinMaxScaler()

In [421]:
#scaler.fit(train_data[numeric_cols])

In [422]:
#train_data[numeric_cols]=scaler.transform(train_data[numeric_cols])
#test_df[numeric_cols]=scaler.transform(test_df[numeric_cols])
#test_data[numeric_cols]=scaler.transform(test_data[numeric_cols])

## Encoding

In [423]:
encoder=OneHotEncoder(sparse=False)

In [424]:
encoder.fit(train_data[cat_cols])

OneHotEncoder(sparse=False, sparse_output=False)

In [425]:
encoded_cols=encoder.get_feature_names_out()
encoded_cols

array(['HomePlanet_Earth', 'HomePlanet_Europa', 'HomePlanet_Mars',
       'CryoSleep_False', 'CryoSleep_True', 'Destination_55 Cancri e',
       'Destination_PSO J318.5-22', 'Destination_TRAPPIST-1e',
       'VIP_False', 'VIP_True'], dtype=object)

In [426]:
train_data[list(encoded_cols)]=encoder.transform(train_data[cat_cols])
test_df[list(encoded_cols)]=encoder.transform(test_df[cat_cols])
test_data[list(encoded_cols)]=encoder.transform(test_data[cat_cols])

In [427]:
train_data

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,CryoSleep_True,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_False,VIP_True
5968,Earth,False,TRAPPIST-1e,40.0,False,1.0,0.0,895.0,10.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
500,Europa,True,55 Cancri e,36.0,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
337,Europa,True,55 Cancri e,21.0,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
3884,Earth,False,TRAPPIST-1e,28.0,False,0.0,241.0,6.0,0.0,542.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3582,Mars,True,TRAPPIST-1e,24.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185,Mars,False,TRAPPIST-1e,27.0,False,1277.0,0.0,1.0,10.0,9.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
7297,Earth,False,TRAPPIST-1e,37.0,False,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
832,Europa,False,55 Cancri e,27.0,False,1.0,12804.0,0.0,10.0,52.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
7324,Europa,True,TRAPPIST-1e,35.0,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2102,Europa,True,55 Cancri e,44.0,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0

In [428]:
model=SVC()

In [429]:
input_cols=list(train_data.columns)[3:]
#test_data['input_cols'].head(5)

In [430]:
model.fit(train_data[input_cols],train_target)

SVC()

In [431]:
predict_val=model.predict(test_df[input_cols])

In [432]:
accuracy_score(test_target,predict_val)

0.8027602070155262

In [433]:
confusion_matrix(test_target,predict_val,normalize='true')

array([[0.70235294, 0.29764706],
       [0.10123735, 0.89876265]])

In [434]:
Transported=model.predict(test_data[input_cols])

In [435]:
result["Transported"]=Transported

In [436]:
result

     PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01         True
...          ...          ...
4272     9266_02         True
4273     9269_01         True
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [ ]:
result.to_csv('Result.csv')